model_list:
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: openai/deepseek-ai/deepseek-v4-pro
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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
  - model_name: claude-3-opus-20240229
    litellm_params:
      model: openai/minimaxai/minimax-m2.7
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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
  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: openai/mistralai/mistral-small-4-119b-2603
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: openai/mistralai/mistral-small-4-119b-2603
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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
  - model_name: pro
    litellm_params:
      model: openai/openai/gpt-oss-120b
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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
  - model_name: fast
    litellm_params:
      model: openai/openai/gpt-oss-20b
      api_base: https://integrate.api.nvidia.com/v1
      api_key: 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
