#!/bin/bash
export ENABLE_TOOL_SEARCH="true"
export ANTHROPIC_BASE_URL="https://v1.iyhapi.app"
export ANTHROPIC_AUTH_TOKEN="iyh_OtGXzOCggfKWzr87qZAy1Jn3LCmxOlPX"
export ANTHROPIC_DEFAULT_OPUS_MODEL="claude-opus-4.8"
export ANTHROPIC_DEFAULT_SONNET_MODEL="claude-sonnet-4.6"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="claude-haiku-4.5"
export ANTHROPIC_MODEL="opus-4.8"
export CLAUDE_CONFIG_DIR="/home/runner/workspace/.config/claude"
claude --model "opus-4.8" "$@"